@baseUrl = http://localhost:4004/odata/v4
###
POST http://localhost:4004/odata/v4/catalog/insertbooks HTTP/1.1
Content-Type: application/json

{
   "borrowerName": "BATMAN",
   "bookTitle": "Power Ranger",
   "authorName": "BBC"

}    
###
POST  http://localhost:4004/odata/v4/catalog/fetchbooks HTTP/1.1
Content-Type: application/json