@baseUrl = http://localhost:4004/odata/v4
@UUID = '89759b16-bfcf-4b13-9629-6cfcbeb019ca'
//INSERT DATA
###
POST {{baseUrl}}/catalog/insertbooks HTTP/1.1
Content-Type: application/json

{
   "borrowerName": "Jeffrey Sumalde",
   "bookTitle": "Pride and Prejudice",
   "authorName": "Jane Austen"

}   
//FETCH DATA 
###
POST  {{baseUrl}}/catalog/fetchbooks HTTP/1.1
Content-Type: application/json

{
   "borrowerName": "Baxter breezy"

}  
//DELETE DATA
###
POST {{baseUrl}}/catalog/deletebooks HTTP/1.1
Content-Type: application/json

{
    "ID": "4c8c0845-d0f8-4bc9-8213-3386dce52cdc"
}

//Send Request for northwind
###
GET http://localhost:4004/odata/v4/catalog/northwind HTTP/1.1



